apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHJmanBvMmFn
  CLOUDINARY_KEY: MzE1ODI4OTU4NTY3NjU3
  CLOUDINARY_SECRET: Nzc1R3U5c3d4aEhzc3BUY1NjOGU4cW5zNV9j
  MAPBOX_TOKEN: cGsuZXlKMUlqb2lhbTl6YUdreU1UQTJJaXdpWVNJNkltTnRjSEZuTlRVd01EQnZkalV6TTNJNVkzcG1iRFkzYlhZaWZRLno3dm9EZ3ZtZFQ2a2tuRlpZd3VaYlE=
  DB_URL: bW9uZ29kYitzcnY6Ly9zaHlhbWpvc2hpa2FsYWdhX2RiX3VzZXI6c1NKTEI0WTlhOFpqZjE5SUBjbHVzdGVyMC4wZnJodG5sLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
